"""
Phase 5 fix: collapse duplicate (loc, rm) records within each property's
quarters-data.js array into a single map feature with merged
reconciliation.csv_matches.

Codex final review (NEEDS-FIXES) found 8 duplicate-loc groups in 3
properties:
  regina-south: 5 groups (NE-3-16-18-W2 x2, NW-3-16-18-W2 x2,
                          SE-3-16-18-W2 x3, NE-34-15-18-W2 x2,
                          SE-35-15-18-W2 x2)
  swift-current: 2 groups (LSD-10-24-13-14-W3 x2, LSD-15-24-13-14-W3 x2)
  vanguard: 1 group (SE-6-12-12-W3 x2)

Each group has different parcel_nos at the same legal location —
extension-variant titles for the same quarter/LSD. Map should render
ONE feature per legal location with all CSV title metadata attached
(matches Codex's "title rows ≠ map features" round-1 rule, applied to
ADDs not just KEEPs).

Strategy:
  For each property, group records by (loc, rm). Within each group,
  pick one canonical record (preferring one with non-null geometry,
  then earliest parcel_no for stability). Merge all other records'
  reconciliation.csv_matches into the canonical record. Drop the rest.

Idempotent: re-runs are no-ops once dedup is complete.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
QUARTERS_PATH = REPO_ROOT / "quarters-data.js"


def load_quarters() -> dict:
    text = QUARTERS_PATH.read_text(encoding="utf-8")
    m = re.search(r"window\.MONETTE_QUARTERS_REAL\s*=\s*(\{.*\})", text, re.DOTALL)
    return json.loads(m.group(1))


def write_quarters(data: dict):
    body = json.dumps(data, separators=(",", ":"), ensure_ascii=False, sort_keys=True)
    header = (
        "// AUTO-GENERATED by scripts/build_quarters_data_js.py.\n"
        "// SK-titles deltas applied via scripts/apply_sk_titles_deltas.py.\n"
        "// Phase 3 fold: __neville__ records folded into vanguard.\n"
        "// Phase 4 polygons: scripts/compute_sk_titles_polygons.py filled\n"
        "// geometry: null records via DLS math.\n"
        "// Phase 5 dedup: scripts/_dedup_quarters_by_loc_rm.py collapsed\n"
        "// duplicate (loc, rm) records into single map features per\n"
        "// Codex final review NEEDS-FIXES finding.\n"
    )
    QUARTERS_PATH.write_text(
        header + f"window.MONETTE_QUARTERS_REAL = {body};\n",
        encoding="utf-8",
    )


def merge_csv_matches(target: dict, source: dict):
    """Append source's csv_matches into target's, dedupe by (title_number, parcel_no, ext)."""
    t_recon = target.setdefault("reconciliation", {})
    s_recon = source.get("reconciliation") or {}
    t_matches = t_recon.setdefault("csv_matches", [])
    seen = {(m.get("title_number"), m.get("parcel_no"), m.get("ext")) for m in t_matches}

    for m in s_recon.get("csv_matches") or []:
        key = (m.get("title_number"), m.get("parcel_no"), m.get("ext"))
        if key in seen:
            continue
        t_matches.append(m)
        seen.add(key)

    # If source had a single csv_match (singular) instead of array, capture it
    if "csv_match" in s_recon and isinstance(s_recon["csv_match"], dict):
        m = s_recon["csv_match"]
        key = (m.get("title_number"), m.get("parcel_no"), m.get("ext"))
        if key not in seen:
            t_matches.append(m)
            seen.add(key)

    # Also note dedup provenance
    notes = t_recon.setdefault("dedup_merged_parcels", [])
    src_pn = source.get("parcel_no")
    if src_pn is not None and src_pn != target.get("parcel_no") and src_pn not in notes:
        notes.append(src_pn)


def pick_canonical(records: list[dict]) -> int:
    """Choose which duplicate record to keep. Prefer non-null geometry; then KEEP/REASSIGN_IN over ADD; then lowest parcel_no for stability."""
    def score(r):
        recon = r.get("reconciliation") or {}
        bucket = recon.get("bucket") or "ZZZ"
        bucket_priority = {
            "KEEP": 0,
            "REASSIGN_IN": 1,
            "ADD": 2,
            "FLAG": 3,
            "REASSIGN_OUT": 4,
        }.get(bucket, 9)
        has_geom = 0 if r.get("geometry") else 1
        pn = r.get("parcel_no")
        try:
            pn_key = int(pn) if pn is not None else 10**18
        except (ValueError, TypeError):
            pn_key = 10**18
        return (has_geom, bucket_priority, pn_key)

    indexed = list(enumerate(records))
    indexed.sort(key=lambda t: score(t[1]))
    return indexed[0][0]


def dedup_property(records: list[dict]) -> tuple[list[dict], int]:
    """Collapse (loc, rm)-duplicate records. Returns (deduped, num_dropped)."""
    groups: dict[tuple, list[int]] = {}
    for i, r in enumerate(records):
        loc = r.get("loc")
        rm = r.get("rm")
        if not loc:
            continue
        key = (loc, rm)
        groups.setdefault(key, []).append(i)

    drop_indices: set[int] = set()
    for key, idxs in groups.items():
        if len(idxs) <= 1:
            continue
        # Choose canonical
        sub = [records[i] for i in idxs]
        canonical_local = pick_canonical(sub)
        canonical_global = idxs[canonical_local]
        # Merge csv_matches from each non-canonical into canonical
        for j, gi in enumerate(idxs):
            if gi == canonical_global:
                continue
            merge_csv_matches(records[canonical_global], records[gi])
            drop_indices.add(gi)

    deduped = [r for i, r in enumerate(records) if i not in drop_indices]
    return deduped, len(drop_indices)


def main():
    quarters = load_quarters()
    summary: dict[str, int] = {}
    for pid, recs in quarters.items():
        deduped, dropped = dedup_property(recs)
        if dropped:
            quarters[pid] = deduped
            summary[pid] = dropped

    write_quarters(quarters)

    if not summary:
        print("No duplicate (loc, rm) groups found — nothing to do (idempotent re-run).")
    else:
        print(f"Collapsed duplicates across {len(summary)} properties:")
        for pid, n in sorted(summary.items()):
            print(f"  {pid}: dropped {n} duplicate record(s); merged csv_matches into canonical")
        print()
        print("Final per-property record counts:")
        for pid in sorted(quarters.keys()):
            print(f"  {pid}: {len(quarters[pid])}")


if __name__ == "__main__":
    main()
