"""
Phase 3 task 1: fold __neville__ records into vanguard.

Per user decision: __neville__ has no standalone property record in
data.js, and its 16 records (14 town lots in Plan N3619 + 2 quarters of
Sec 6-12-12-W3 reassigned from vanguard in Wave C) sit ~17km SW of
Vanguard's anchor. Fold into vanguard and remove the __neville__ key
from quarters-data.js.

This is a one-off migration script (underscore-prefixed transient). The
parse_isc_titles.py RM_TO_PROPERTY crosswalk is updated separately so
future re-runs of the pipeline map "VILLAGE OF NEVILLE" -> vanguard
directly (idempotent).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
QUARTERS_PATH = REPO_ROOT / "quarters-data.js"


def load_quarters() -> dict:
    text = QUARTERS_PATH.read_text(encoding="utf-8")
    m = re.search(r"window\.MONETTE_QUARTERS_REAL\s*=\s*(\{.*\})", text, re.DOTALL)
    if not m:
        sys.exit("Could not parse quarters-data.js")
    return json.loads(m.group(1))


def write_quarters(data: dict):
    body = json.dumps(data, separators=(",", ":"), ensure_ascii=False, sort_keys=True)
    header = (
        "// AUTO-GENERATED by scripts/build_quarters_data_js.py.\n"
        "// SK-titles deltas applied via scripts/apply_sk_titles_deltas.py.\n"
        "// Phase 3 fold: __neville__ records folded into vanguard.\n"
        "// Re-run build_quarters_data_js.py + apply_sk_titles_deltas.py to regenerate.\n"
    )
    QUARTERS_PATH.write_text(
        header + f"window.MONETTE_QUARTERS_REAL = {body};\n",
        encoding="utf-8",
    )


def main():
    quarters = load_quarters()
    if "__neville__" not in quarters:
        print("__neville__ not present — nothing to fold")
        return

    neville_recs = quarters["__neville__"]
    if not neville_recs:
        del quarters["__neville__"]
        write_quarters(quarters)
        print("__neville__ was empty; removed key")
        return

    vanguard_recs = quarters.setdefault("vanguard", [])

    # Build dedup set of vanguard parcel_nos so re-runs are idempotent
    vanguard_pns = {
        str(r.get("parcel_no")) for r in vanguard_recs if r.get("parcel_no") is not None
    }

    moved = 0
    for rec in neville_recs:
        rec_pn = str(rec.get("parcel_no")) if rec.get("parcel_no") is not None else None
        if rec_pn and rec_pn in vanguard_pns:
            # Already in vanguard via prior fold; skip
            continue
        # Annotate reconciliation: keep the existing bucket but record the fold
        recon = rec.setdefault("reconciliation", {})
        recon["folded_from"] = "__neville__"
        recon["fold_decision"] = (
            "Phase 3 anchor decision: __neville__ has no standalone "
            "data.js property record. Folded into vanguard (closest "
            "property anchor, ~17km NE of Neville village)."
        )
        recon["fold_date"] = "2026-05-01"
        vanguard_recs.append(rec)
        if rec_pn:
            vanguard_pns.add(rec_pn)
        moved += 1

    del quarters["__neville__"]
    write_quarters(quarters)

    print(f"Folded {moved} records from __neville__ into vanguard")
    print(f"vanguard now has {len(vanguard_recs)} records")
    print(f"__neville__ key removed from quarters-data.js")


if __name__ == "__main__":
    main()
