"""
Apply ISC-CSV-derived deltas to quarters-data.js.

Inputs:
  quarters-data.js                                  (current map source of truth)
  <deltas.json>                                     (e.g. docs/logs/sk-titles/wymark/proposed-deltas.json)

Output:
  quarters-data.js                                  (in-place rewrite)

Operation:
  For each property in the deltas file, replace the current quarters[pid] array
  with the union of the delta's buckets (keep + flag + add + reassign_in).
  Codex's delta format already contains complete records ready for slot-in,
  with reconciliation metadata pre-baked. We trust the delta is the desired
  full state for the property.

  reassign_out is NOT applied to the source property's array (those records
  are leaving — they appear in the target property's reassign_in bucket).

  remove is never honored — anchor-truth principle says do not delete.

Idempotency:
  Re-running with the same deltas file produces the same final quarters-data.js
  because every property is replaced wholesale from the delta buckets.

Verification:
  Per-property record counts before/after are reported. The script also writes
  a `_reconciliation_provenance` block to every property's array via a header
  in the output (commented JS line above the data).

Usage:
  python scripts/apply_sk_titles_deltas.py docs/logs/sk-titles/wymark/proposed-deltas.json

To revert:
  cp quarters-data.js.bak.pre-sk-titles quarters-data.js
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
QUARTERS_PATH = REPO_ROOT / "quarters-data.js"


def load_quarters() -> dict:
    text = QUARTERS_PATH.read_text(encoding="utf-8")
    m = re.search(r"window\.MONETTE_QUARTERS_REAL\s*=\s*(\{.*\})", text, re.DOTALL)
    if not m:
        sys.exit("Could not parse quarters-data.js — missing window.MONETTE_QUARTERS_REAL")
    return json.loads(m.group(1))


def write_quarters(data: dict, deltas_path: str, snapshot_date: str):
    body = json.dumps(data, separators=(",", ":"), ensure_ascii=False, sort_keys=True)
    header = (
        "// AUTO-GENERATED by scripts/build_quarters_data_js.py.\n"
        f"// SK-titles deltas applied by scripts/apply_sk_titles_deltas.py from {deltas_path} (snapshot {snapshot_date}).\n"
        "// Re-run build_quarters_data_js.py to regenerate from XLSX, then re-run\n"
        "// apply_sk_titles_deltas.py to re-apply CSV-derived reconciliation.\n"
    )
    QUARTERS_PATH.write_text(
        header + f"window.MONETTE_QUARTERS_REAL = {body};\n",
        encoding="utf-8",
    )


def main(deltas_path: str):
    deltas = json.loads(Path(deltas_path).read_text(encoding="utf-8"))
    snapshot_date = deltas.get("snapshot_date", "unknown")
    quarters = load_quarters()

    before = {pid: len(arr) for pid, arr in quarters.items()}
    summary: dict[str, dict[str, int]] = {}
    affected_pids: set[str] = set()

    for pid, p in deltas.get("properties", {}).items():
        # Skip only the explicit Codex-convention metadata block.
        # Placeholder pids like __neville__ are real data buckets and
        # must be processed.
        if pid == "_other_affected":
            continue
        affected_pids.add(pid)
        new_records: list[dict] = []
        bucket_counts = {"keep": 0, "flag": 0, "add": 0, "reassign_in": 0, "reassign_out_skipped": 0}

        for bucket in ("keep", "flag", "add", "reassign_in"):
            for rec in p.get(bucket, []):
                if not isinstance(rec, dict) or "loc" not in rec:
                    print(f"  WARN: {pid}/{bucket} entry missing 'loc', skipping: {rec}")
                    continue
                new_records.append(rec)
                bucket_counts[bucket] += 1

        # reassign_out: confirm count for verification, but the records themselves
        # are NOT applied to the source property — they appear in the target's
        # reassign_in bucket. We just confirm they exist.
        bucket_counts["reassign_out_skipped"] = len(p.get("reassign_out", []))

        if "remove" in p and p["remove"]:
            print(f"  WARN: {pid} delta has non-empty 'remove' bucket — anchor-truth principle says do not delete. Ignoring.")

        quarters[pid] = new_records
        summary[pid] = bucket_counts

    write_quarters(quarters, deltas_path, snapshot_date)

    after = {pid: len(arr) for pid, arr in quarters.items()}

    print(f"Applied deltas from {deltas_path}")
    print(f"Snapshot date: {snapshot_date}")
    print()
    print(f"  {'property':<20} {'before':>7} {'after':>7} {'KEEP':>5} {'FLAG':>5} {'ADD':>5} {'RAIn':>5} {'RAOut*':>7}")
    for pid in sorted(affected_pids):
        s = summary[pid]
        b = before.get(pid, 0)
        a = after.get(pid, 0)
        delta = f"{a - b:+d}" if a != b else "0"
        print(f"  {pid:<20} {b:>7} {a:>7} {s['keep']:>5} {s['flag']:>5} {s['add']:>5} {s['reassign_in']:>5} {s['reassign_out_skipped']:>7}  ({delta})")
    print()
    print("  RAOut* = count from delta (verifies symmetry with target's RAIn) — not applied to source array.")
    print()
    print(f"To revert: cp quarters-data.js.bak.pre-sk-titles quarters-data.js")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("Usage: python scripts/apply_sk_titles_deltas.py <path/to/deltas.json>")
    main(sys.argv[1])
