import { copyFile, cp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { transform } from "esbuild";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");
const outDir = path.join(root, "build");
const deployRootDir = path.join(root, "public");
const deployBuildDir = path.join(deployRootDir, "build");
const deployDossierDir = path.join(deployRootDir, "dossiers");
const graphicsDir = path.join(root, "graphics");
const deployGraphicsDir = path.join(deployRootDir, "graphics");

// Load .env.local into process.env if present so local builds pick up secrets
// without requiring a shell export. Vercel injects env vars natively.
const envLocalPath = path.join(root, ".env.local");
if (existsSync(envLocalPath)) {
  for (const line of readFileSync(envLocalPath, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (!m) continue;
    const key = m[1];
    let val = m[2];
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = val;
  }
}

// Render config.template.js → ./config.js and ./public/config.js with secret
// substitution. Source-of-truth for the template lives in git; the rendered
// outputs are gitignored so the literal token never enters history.
async function renderConfig() {
  const templatePath = path.join(root, "config.template.js");
  const template = await readFile(templatePath, "utf8");
  const mapboxToken = process.env.MAPBOX_TOKEN;
  if (!mapboxToken) {
    throw new Error(
      "MAPBOX_TOKEN is not set. Add it to .env.local (local) or Vercel project env vars (deploy)."
    );
  }
  const rendered = template.replace(/__MAPBOX_TOKEN__/g, mapboxToken);
  await writeFile(path.join(root, "config.js"), rendered, "utf8");
  console.log("rendered config.template.js -> config.js");
}

const entries = [
  "components.jsx",
  "quarter-panel.jsx",
  "property-drawer.jsx",
  "view-list.jsx",
  "view-creditors.jsx",
  "view-group-structure.jsx",
  "view-debt-stack.jsx",
  "view-map.jsx",
  "view-dossier.jsx",
  "app.jsx",
];

const staticAssets = [
  "index.html",
  "config.js",
  "data.js",
  "creditors-data.js",
  "imagery-data.js",
  "quarter-owners.js",
  "quarters-data.js",
  "quarters.js",
  "supabase-client.js",
  "styles.css",
  "favicon.svg",
];

// Dossier files are plain JS modules registered on window.MONETTE_DOSSIERS.
// They're copied verbatim from /dossiers into /public/dossiers.
const dossiersDir = path.join(root, "dossiers");

// Clean both build dirs before rebuilding so deleted source files (e.g.,
// view-editorial.jsx removed in 4263315) can't leave stale compiled
// artifacts behind. Previously only public/ was cleaned; build/ accumulated
// stale .js files indefinitely. Deploy was always correct because Vercel
// only ships public/, but local debugging could mislead anyone reading
// build/ directly. Codex post-cleanup-review flag, fixed 2026-04-29.
await rm(outDir, { recursive: true, force: true });
await rm(deployRootDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });
await mkdir(deployBuildDir, { recursive: true });
await mkdir(deployDossierDir, { recursive: true });

// Render the config from template + env BEFORE the static-asset copy so
// the resolved file is what gets shipped to public/.
await renderConfig();

for (const entry of entries) {
  const sourcePath = path.join(root, entry);
  let source;
  try {
    source = await readFile(sourcePath, "utf8");
  } catch (err) {
    if (err && err.code === "ENOENT") {
      console.warn(`skip missing ${entry}; keeping any existing compiled output`);
      continue;
    }
    throw err;
  }
  const { code } = await transform(source, {
    loader: "jsx",
    jsx: "transform",
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
    target: "es2019",
    sourcemap: false,
  });

  const outName = entry.replace(/\.jsx$/, ".js");
  const outPath = path.join(outDir, outName);
  const compiled = `// AUTO-GENERATED by scripts/build-jsx.mjs\n// Source: ${entry}\n${code}`;
  await writeFile(outPath, compiled, "utf8");
  await writeFile(path.join(deployBuildDir, outName), compiled, "utf8");
  console.log(`built ${path.relative(root, outPath)}`);
}

for (const asset of staticAssets) {
  const sourcePath = path.join(root, asset);
  const destPath = path.join(deployRootDir, asset);
  await copyFile(sourcePath, destPath);
  console.log(`copied ${asset} -> ${path.relative(root, destPath)}`);
}

try {
  await cp(graphicsDir, deployGraphicsDir, { recursive: true });
  console.log(`copied graphics -> ${path.relative(root, deployGraphicsDir)}`);
} catch (err) {
  if (err && err.code === "ENOENT") {
    console.warn("no /graphics directory; skipping graphics copy");
  } else {
    throw err;
  }
}

// Copy every .js file in /dossiers verbatim. Each dossier registers itself on
// window.MONETTE_DOSSIERS and is loaded via <script src="dossiers/{name}.js">.
try {
  const dossierFiles = await readdir(dossiersDir);
  for (const file of dossierFiles) {
    if (!file.endsWith(".js")) continue;
    const srcPath = path.join(dossiersDir, file);
    const destPath = path.join(deployDossierDir, file);
    await copyFile(srcPath, destPath);
    console.log(`copied dossiers/${file} -> ${path.relative(root, destPath)}`);
  }
} catch (err) {
  if (err && err.code === "ENOENT") {
    console.warn("no /dossiers directory; skipping dossier copy");
  } else {
    throw err;
  }
}
