"""
Build imagery-data.js for the Monette atlas.

v2 (rev 4): graduated from placeholder to GEE-driven via the
gee_pipeline package. For Phase 2 (this plan), the script accepts a
--parcels-list JSON file specifying which parcels to process; default
is the Hafford property (158 parcels).

Phases 3 onwards expand the parcel list and add territory shards.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

# Bootstrap: ensure scripts/ is on sys.path so we can import the
# gee_pipeline package whether this file is run as
# `python scripts/build_imagery_data_js.py` or
# `python -m scripts.build_imagery_data_js`. Mirrors the pattern used in
# scripts/gee_pipeline/pipeline.py and scripts/gee_pipeline/t0_baseline.py.
_HERE = Path(__file__).resolve()
for _parent in _HERE.parents:
    if _parent.name == "scripts":
        if str(_parent) not in sys.path:
            sys.path.insert(0, str(_parent))
        break

ROOT = Path(__file__).resolve().parent.parent
GEOJSON = ROOT / "quarters.geojson"
OUT = ROOT / "imagery-data.js"
PUBLIC_OUT = ROOT / "public" / "imagery-data.js"


def iso_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def load_parcel_index() -> dict:
    """Load quarters.geojson and index features by (property_id, loc)."""
    data = json.loads(GEOJSON.read_text(encoding="utf-8"))
    index = {}
    by_property = Counter()
    for feature in data.get("features", []):
        props = feature.get("properties") or {}
        prop_id = props.get("property_id")
        loc = props.get("loc")
        if not (prop_id and loc):
            continue
        index[f"{prop_id}:{loc}"] = props
        by_property[prop_id] += 1
    return {
        "total_features": sum(by_property.values()),
        "by_property": dict(sorted(by_property.items())),
        "lookup": index,
    }


def build_payload(parcel_keys: list[str], run_date: str) -> dict:
    """Run the GEE pipeline for each parcel in parcel_keys."""
    from gee_pipeline.auth import initialize
    from gee_pipeline.pipeline import run_single_parcel

    initialize()
    coverage = load_parcel_index()
    parcels_out = {}

    total = len(parcel_keys)
    for i, key in enumerate(parcel_keys, start=1):
        prop_id, loc = key.split(":", 1)
        print(f"  [{i}/{total}] {key} ...", flush=True)
        try:
            record = run_single_parcel(
                property_id=prop_id, loc=loc, run_date=run_date
            )
        except Exception as exc:  # noqa: BLE001
            record = {
                "status": "error",
                "error": str(exc),
                "image_from": run_date,
                "image_to": run_date,
            }
        parcels_out[key] = record

    # Fix (Codex b08awunq3): fail closed when any parcel errored.
    # Previously the script exited 0 with ready:True even if some parcels had
    # status:"error", making a partial-failure run indistinguishable from a
    # clean one. Now we count error records, print diagnostics, and raise
    # SystemExit(2) — leaving the prior output file intact rather than
    # overwriting it with a half-broken payload.
    error_keys = [k for k, v in parcels_out.items() if v.get("status") == "error"]
    if error_keys:
        print(
            f"\nPHASE 5 FAILED: {len(error_keys)} parcel(s) errored.",
            file=sys.stderr,
        )
        for key in error_keys[:3]:
            print(
                f"  {key}: {parcels_out[key].get('error', '(no message)')}",
                file=sys.stderr,
            )
        if len(error_keys) > 3:
            print(f"  ... and {len(error_keys) - 3} more.", file=sys.stderr)
        raise SystemExit(2)

    return {
        "generated_at": iso_now(),
        "source": "gee-pipeline",
        "ready": True,
        "window_days": 14,
        "thresholds_version": "v1.0-prior",
        "coverage": {
            "mapped_parcels": coverage["total_features"],
            "mapped_properties": len(coverage["by_property"]),
            "by_property": coverage["by_property"],
        },
        "parcels": parcels_out,
    }


def write_js(payload: dict) -> None:
    body = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    PUBLIC_OUT.parent.mkdir(parents=True, exist_ok=True)
    for path in (OUT, PUBLIC_OUT):
        path.write_text(
            "// AUTO-GENERATED by scripts/build_imagery_data_js.py\n"
            "// GEE-driven payload - Phase 2 scaffold (Hafford-only by default).\n"
            f"window.MONETTE_IMAGERY = {body};\n",
            encoding="utf-8",
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build imagery-data.js by calling the GEE pipeline."
    )
    parser.add_argument("--property-id", default="hafford",
                        help="Process only parcels under this property_id (default: hafford).")
    parser.add_argument("--run-date", default="2026-04-28",
                        help="ISO date for T1 window end.")
    parser.add_argument("--limit", type=int, default=None,
                        help="Process at most N parcels (useful for smoke tests).")
    parser.add_argument("--parcels-list", type=str, default=None,
                        help="Optional path to a JSON file with a list of "
                             "'property_id:loc' keys. Overrides --property-id "
                             "filtering when provided.")
    args = parser.parse_args()

    coverage = load_parcel_index()

    if args.parcels_list:
        keys = json.loads(Path(args.parcels_list).read_text(encoding="utf-8"))
        if not isinstance(keys, list):
            raise SystemExit("--parcels-list must be a JSON list of 'property_id:loc' strings.")
        # Validate keys exist in the index
        missing = [k for k in keys if k not in coverage["lookup"]]
        if missing:
            raise SystemExit(f"Unknown parcel keys: {missing[:5]} (and {max(0,len(missing)-5)} more)")
        scope_label = f"explicit list ({len(keys)} parcels)"
    else:
        keys = [k for k in coverage["lookup"]
                if k.startswith(f"{args.property_id}:")]
        scope_label = f"property_id={args.property_id}"

    if args.limit:
        keys = keys[:args.limit]

    print(f"Processing {len(keys)} parcels — scope: {scope_label}, run_date={args.run_date}")
    payload = build_payload(keys, args.run_date)
    write_js(payload)
    print(f"Wrote {OUT.name} and {PUBLIC_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
