"""
Reads ../quarters.geojson and emits ../quarters-data.js as:
  window.MONETTE_QUARTERS_REAL = { "<property_id>": [ {loc, ac, ...}, ... ], ... };

Keeps only fields the drawer and map actually need — geometry is stored
per-quarter so the map layer can render polygons without re-fetching the
geojson.

Field map (source → output):
  properties.property_id → outer dict key (not included in row)
  properties.titled_ac   → ac
  properties.crop_2025   → crop
  properties.loc/soil/assessment/rm/parcel_no/title → same name
  public-source fields such as owner, tax_year, source, and property_card are
  preserved when present so parcel rows can explain their provenance.
  geometry               → slimmed Polygon (6-dp rounded) or None
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEOJSON = ROOT / "quarters.geojson"
OUT = ROOT / "quarters-data.js"

def round_coord(c, ndigits=6):
    """Round lon/lat to 6 dp (~0.1 m) to trim file size without losing fidelity."""
    return round(c, ndigits)

def slim_geometry(geom):
    if not geom or geom.get("type") != "Polygon":
        return None
    coords = geom["coordinates"]
    return {
        "type": "Polygon",
        "coordinates": [
            [[round_coord(x), round_coord(y)] for x, y in ring]
            for ring in coords
        ],
    }

def main():
    data = json.loads(GEOJSON.read_text(encoding="utf-8"))
    by_prop: dict[str, list[dict]] = {}
    for feat in data["features"]:
        p = feat["properties"]
        pid = p.get("property_id")
        if not pid:
            print(f"WARNING: feature missing property_id, skipping: loc={p.get('loc')!r}")
            continue
        row = {
            "loc": p.get("loc"),
            "ac": p.get("titled_ac") or 0,
            "gis_ac": p.get("gis_ac"),
            "soil": p.get("soil"),
            "crop": p.get("crop_2025"),
            "assessment": p.get("assessment"),
            "rm": p.get("rm"),
            "parcel_no": p.get("parcel_no") or p.get("parcel_id"),
            "owner": p.get("owner"),
            "tax_year": p.get("tax_year"),
            "source": p.get("source"),
            "property_card": p.get("property_card"),
            "title": p.get("title"),
            "geometry": slim_geometry(feat.get("geometry")),
        }
        by_prop.setdefault(pid, []).append(row)

    # Sort each property's rows by (loc, parcel_no) so the output is fully
    # deterministic even when rows share a null loc.
    for pid in by_prop:
        by_prop[pid].sort(key=lambda r: (r["loc"] or "", str(r["parcel_no"] or "")))

    # Downstream uses q.loc as a React key and a scroll-into-view anchor, so
    # duplicate locs within a property would silently break those paths.
    # Warn early if the pipeline ever emits a non-unique loc.
    for pid, rows in by_prop.items():
        seen = {}
        for r in rows:
            if r["loc"]:
                seen[r["loc"]] = seen.get(r["loc"], 0) + 1
        dups = {loc: n for loc, n in seen.items() if n > 1}
        if dups:
            print(f"WARNING: {pid} has duplicate locs: {dups}")

    # sort_keys makes the outer dict order stable regardless of feature order
    # in the input geojson.
    body = json.dumps(by_prop, separators=(",", ":"), ensure_ascii=False, sort_keys=True)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/build_quarters_data_js.py\n"
        "// Do not edit by hand. Re-run the script after updating quarters.geojson.\n"
        f"window.MONETTE_QUARTERS_REAL = {body};\n",
        encoding="utf-8",
    )
    total = sum(len(v) for v in by_prop.values())
    print(f"Wrote {OUT.name}: {len(by_prop)} properties, {total} quarters, {OUT.stat().st_size:,} bytes")

if __name__ == "__main__":
    main()
