"""
Build imagery-data.js for the Monette atlas.

This initial version writes a placeholder payload so the map UI can read a
stable window.MONETTE_IMAGERY contract without exposing browser-side imagery
credentials. Replace the placeholder generation with real Sentinel parcel
stats before shipping the public vigor layer.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
GEOJSON = ROOT / "quarters.geojson"
OUT = ROOT / "imagery-data.js"


def iso_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def load_quarter_counts() -> tuple[int, Counter]:
    data = json.loads(GEOJSON.read_text(encoding="utf-8"))
    features = data.get("features", [])
    by_property = Counter()
    for feature in features:
        props = feature.get("properties") or {}
        prop_id = props.get("property_id")
        if prop_id:
            by_property[prop_id] += 1
    return len(features), by_property


def build_placeholder(window_days: int) -> dict:
    total_features, by_property = load_quarter_counts()
    return {
        "generated_at": iso_now(),
        "source": "placeholder",
        "window_days": window_days,
        "ready": False,
        "note": (
            "Vegetation vigor is wired to a generated asset, but live parcel "
            "imagery has not been built yet."
        ),
        "coverage": {
            "mapped_parcels": total_features,
            "mapped_properties": len(by_property),
            "by_property": dict(sorted(by_property.items())),
        },
        "parcels": {},
    }


def write_js(payload: dict) -> None:
    body = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/build_imagery_data_js.py\n"
        "// Placeholder build: replace this with real parcel stats before shipping vigor publicly.\n"
        f"window.MONETTE_IMAGERY = {body};\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Build imagery-data.js placeholder contract.")
    parser.add_argument("--window-days", type=int, default=21, help="Rolling imagery window shown in the UI.")
    args = parser.parse_args()

    payload = build_placeholder(args.window_days)
    write_js(payload)

    coverage = payload["coverage"]
    print(f"Wrote {OUT.name}")
    print(f"  generated_at: {payload['generated_at']}")
    print(f"  mapped_properties: {coverage['mapped_properties']}")
    print(f"  mapped_parcels: {coverage['mapped_parcels']}")
    print(f"  window_days: {payload['window_days']}")
    print("  populated_imagery_rows: 0 (placeholder build)")


if __name__ == "__main__":
    main()
