-- Migration: drop all voting-related tables, views, and functions
-- Generated by the satellite pivot (Codex pressure-test b05w54lpy), 2026-04-29
--
-- IMPORTANT: DO NOT EXECUTE until the satellite pivot is confirmed stable
-- in production and all community-vote feature flags have been removed from
-- all deployed clients. The vote data is unrecoverable after this migration.
--
-- Supabase free-tier note: the supabase-client.js now sets the global
-- window.SUPA_DISABLED = true before any DB calls, so no client is writing
-- to these tables. This migration is the final cleanup step — safe to run
-- once the Vercel deployment of Commit 5 has been live for 24+ hours.

BEGIN;

-- Drop views first (they depend on the tables below)
DROP VIEW IF EXISTS public.vote_activity_feed;
DROP VIEW IF EXISTS public.vote_latest_seeded_per_prop;
DROP VIEW IF EXISTS public.vote_tallies;

-- Drop the server-side RPC that clients called to insert votes
DROP FUNCTION IF EXISTS public.submit_vote(
  uuid, text, text, text, text, text
);

-- Drop aggregation / state tables that were populated by the views/triggers
DROP TABLE IF EXISTS public.quarter_current_state;

-- Drop the base votes table last (all other objects depended on it)
DROP TABLE IF EXISTS public.votes;

COMMIT;
