-- Migration: drop all voting-related views, function, and base table
-- Generated by the satellite pivot (Codex pressure-test b05w54lpy + post-
-- review fixes from bwgf1888o), 2026-04-29.
--
-- IMPORTANT: DO NOT EXECUTE until the Vercel deployment of the pivot
-- commits (43f6a98..HEAD) has been live for ~24 hours so deployed clients
-- have stopped issuing vote reads/writes. The vote data is unrecoverable
-- after this migration.
--
-- Schema reference (from supabase/migrations/):
--   - public.votes                       — base table (20260422000000_init.sql)
--   - public.vote_activity_feed          — VIEW (20260423090000)
--   - public.vote_latest_seeded_per_prop — VIEW (20260423090000)
--   - public.vote_tallies                — VIEW (20260422000000_init.sql)
--   - public.quarter_current_state       — VIEW (20260425150000_homepage_voting_board.sql:12)
--   - public.submit_vote(text, text, text, text, text, text)
--                                        — FUNCTION (20260425150000:67, signature
--                                          confirmed; uuid version never existed)

BEGIN;

-- Drop dependent views first
DROP VIEW IF EXISTS public.vote_activity_feed;
DROP VIEW IF EXISTS public.vote_latest_seeded_per_prop;
DROP VIEW IF EXISTS public.vote_tallies;
DROP VIEW IF EXISTS public.quarter_current_state;

-- Drop the server-side RPC that clients called to insert votes.
-- Signature must match exactly — Postgres function overloading is signature-
-- based, and the migration in 20260425150000 created submit_vote(text x6).
DROP FUNCTION IF EXISTS public.submit_vote(
  text, text, text, text, text, text
);

-- Drop the base votes table last (all other objects depended on it)
DROP TABLE IF EXISTS public.votes;

COMMIT;

-- Post-migration verification (run separately in psql):
--   \d+ public.votes                   -- expected: relation does not exist
--   \d+ public.vote_tallies            -- expected: relation does not exist
--   \d+ public.quarter_current_state   -- expected: relation does not exist
--   \df public.submit_vote             -- expected: no rows
--   \d+ public.tips                    -- expected: still exists, untouched
--   SELECT count(*) FROM public.tips;  -- expected: row count preserved
